### ISSUE TITLE
Add grouping functionality

### ISSUE THREAD

**Issue by JeremyTheocharis** [united-manufacturing-hub/umh-datasource-v2#10]
This should be used when you want to add your own tags to the UMH. By using underscores in the tagname, you can group them and they will be shown as a separate group in Grafana. For example: temperatures_head and temperatures_bottom will be shown together as a group called temperatures

**Comment by DaruZero** [comment]
Closed in [v1.0.74](https://github.com/united-manufacturing-hub/umh-datasource-v2/releases/tag/v1.0.74)
