### ISSUE TITLE
Value selection is always empty

### ISSUE THREAD

**Issue by Scarjit** [united-manufacturing-hub/umh-datasource-v2#6]
When creating a graph, the Value field will appear empty, if you edit it, after creation.

**Comment by DaruZero** [comment]
Content of the Value Cascader is not consistent. For example switching between visualization type most of the time won't show the actual value of the Cascader. Inerting a breakpoint on the Cascader component will always result in the correct visualizaiton of the value. 
Maybe is some sort of race condition?
