### ISSUE TITLE
Allow return of raw datapoints

### ISSUE THREAD

**Issue by Scarjit** [united-manufacturing-hub/umh-datasource-v2#7]
We need a function to return non-bucketet data

**Comment by DaruZero** [comment]
Related to united-manufacturing-hub/united-manufacturing-hub#1329

There should be a toggle for the time bucket query option. If the toggle is on than the user can access a dropdown menu with the unit of measure (minutes, hours, etc) and numeric input fot the quantity. If the toggle is off than no time bucket will be used for the query

**Comment by DaruZero** [comment]
Issue blocked by https://github.com/united-manufacturing-hub/united-manufacturing-hub/issues/1335

**Comment by DaruZero** [comment]
Closed by united-manufacturing-hub/united-manufacturing-hub#1342
